# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Quantified Golf
# Description of the Site
description: Better Golfing Through Data
# URL of Image of the Site
site-image: /assets/images/logo.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/background.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: will@quantifiedgolf.com
facebook_username: 
twitter_username: QuantifiedGolf
instagram_username: QuantifiedGolf
#linkedin_username: thedevslot
github_username:  willwagner
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: 
behance_username: 
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: G-LP97KRWVVZ

# Disqus
disqus-shortname: quantified-golf

# Name of the Author
author-name: Will Wagner
author-image: /assets/images/logo.png
# URL for the Image of the Author
#author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: I'm an SF Bay Area techie who's passionate about golf
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linkedin.com/m/willwagner/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
